### ISSUE TITLE
Feature: Blueprints

### ISSUE THREAD

**Issue by JerkyTreats** [JerkyTreats/EndlessHorizons#9]
When the player drag and drops a component onto the grid, that component is added to the currently active `blueprint`. 

Blueprints allow for the saving and loading of different ships. It will also have implications for gameplay. 

## Adding Components to Blueprints

This relates to `PlacementHandler.onEndDrag()` (?). When the object is being spawned, the object should be added to the currently active blueprint. 

Additionally, the blueprint should have a Game Object. On end drag, the instantiated Ship Component should be added as a child to blueprint. (This will allow for a clean object list, as well as easily destruction of the blueprint when a new one is to be loaded). 

##### Tasks
- [x] Object is added to the blueprint on drop
- [x] Spawned Game Object is a child of the Blueprint Game Object
- [x] Blueprint GameObject added to GameData instance

### Blueprint Component

The object itself is not added to the blueprint, instead a `BlueprintComponent` is added, which can be used to represent the object off disk. The component will eventually be converted into a JSON file to act as disk/cloud storage. 

`BlueprintComponent` is a `struct` that contains a Vector3 `GridLocation` of the object being added. Additionally, it needs to know what object to build. Since things will be saved off-disk, object references cannot be used. 

To get around this, a `Component Enum` will be created and stored as a string, along with the  `Name` associated with the data object. The `ComponentRepository` then needs a method to return the correct data type. We might be able to get away with this using a generic return type. If not, we have to figure out how to generate the Data object from the blueprint. 

#### Other Ideas

- Have a Component manifest, that acts a single point of entry.
- TileData has a factory method passing in the FilePath to use.  
  - Blueprint stores the FilePath. Still need to figure out how to call that it is a Tile/other component. 

##### Tasks
- [x] `Components` Added to `Blueprint` on Drop
- [x] Component added as a `BlueprintComponent` struct
- [x] BlueprintComponent struct uses JSONable primitives

## Collision detection on drop asks blueprint if tile is occupied

Currently collision detection is being handled by the `GridTile` determining if there is any occupying component. This is to be refactored to be the blueprint determining collision. To start, only 1 type of each component is allowed to occupy a single GridTile. That means you can have 1 Tile, Equipment occupy the same tile. 

##### Tasks
- [x] Remove tile occupation code from `GridTile`
- [x] Add tile occupation code to `Blueprint`
- [x] Update `PlacementHandler` accordingly

**Comment by JerkyTreats** [comment]
Tasks completed and integrated in #13
